<?php

/**
 * @file
 * Functions to support theming in the Pattern Lab theme.
 */

/**
 * Implements hook_preprocess().
 */
function wcm8_emulsify_preprocess(array &$variables, $hook) {
  $variables['base_path'] = base_path();
}

function wcm8_emulsify_preprocess_page(array &$variables) {
  // Load the site name out of configuration.
  $config = \Drupal::config('system.site');
  $variables['site_name'] = $config->get('name');
}